name: Daily Tweet

on:
  schedule:
    - cron: '10 13 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        node-version: '16'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        node-version: '16'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests tweepy googletrans

    - name: Run script
      run: |
        python main.py
